// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/lucasbrito3001/ticketflow-reservation-service/internal/app/usecases/dto"
	mock "github.com/stretchr/testify/mock"
)

// CreateReservationUseCase is an autogenerated mock type for the CreateReservationUseCase type
type CreateReservationUseCase struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, input
func (_m *CreateReservationUseCase) Execute(ctx context.Context, input *dto.CreateReservationInput) (*dto.CreateReservationOutput, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *dto.CreateReservationOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.CreateReservationInput) (*dto.CreateReservationOutput, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.CreateReservationInput) *dto.CreateReservationOutput); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.CreateReservationOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.CreateReservationInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCreateReservationUseCase creates a new instance of CreateReservationUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCreateReservationUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *CreateReservationUseCase {
	mock := &CreateReservationUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
