// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	reservation "github.com/lucasbrito3001/ticketflow-reservation-service/internal/domain/reservation"
)

// InventoryServiceClient is an autogenerated mock type for the InventoryServiceClient type
type InventoryServiceClient struct {
	mock.Mock
}

// HoldTickets provides a mock function with given fields: ctx, eventID, tickets
func (_m *InventoryServiceClient) HoldTickets(ctx context.Context, eventID int64, tickets map[reservation.ReservationTicketType]int) error {
	ret := _m.Called(ctx, eventID, tickets)

	if len(ret) == 0 {
		panic("no return value specified for HoldTickets")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, map[reservation.ReservationTicketType]int) error); ok {
		r0 = rf(ctx, eventID, tickets)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewInventoryServiceClient creates a new instance of InventoryServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInventoryServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *InventoryServiceClient {
	mock := &InventoryServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
