// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	reservation "github.com/lucasbrito3001/ticketflow-reservation-service/internal/domain/reservation"
)

// ReservationRepository is an autogenerated mock type for the ReservationRepository type
type ReservationRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, ticket
func (_m *ReservationRepository) Create(ctx context.Context, ticket *reservation.Reservation) (int64, error) {
	ret := _m.Called(ctx, ticket)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *reservation.Reservation) (int64, error)); ok {
		return rf(ctx, ticket)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *reservation.Reservation) int64); ok {
		r0 = rf(ctx, ticket)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *reservation.Reservation) error); ok {
		r1 = rf(ctx, ticket)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindById provides a mock function with given fields: ctx, ticketID
func (_m *ReservationRepository) FindById(ctx context.Context, ticketID string) (*reservation.Reservation, error) {
	ret := _m.Called(ctx, ticketID)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 *reservation.Reservation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*reservation.Reservation, error)); ok {
		return rf(ctx, ticketID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *reservation.Reservation); ok {
		r0 = rf(ctx, ticketID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reservation.Reservation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, ticketID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, ticket
func (_m *ReservationRepository) Update(ctx context.Context, ticket *reservation.Reservation) error {
	ret := _m.Called(ctx, ticket)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *reservation.Reservation) error); ok {
		r0 = rf(ctx, ticket)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewReservationRepository creates a new instance of ReservationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReservationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReservationRepository {
	mock := &ReservationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
