// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/lucasbrito3001/ticketflow-inventory-service/internal/app/usecases/dto"
	mock "github.com/stretchr/testify/mock"
)

// ConsumeTicket is an autogenerated mock type for the ConsumeTicket type
type ConsumeTicket struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, command
func (_m *ConsumeTicket) Execute(ctx context.Context, command dto.ConsumeTicketInput) (*dto.ConsumeTicketOutput, error) {
	ret := _m.Called(ctx, command)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *dto.ConsumeTicketOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.ConsumeTicketInput) (*dto.ConsumeTicketOutput, error)); ok {
		return rf(ctx, command)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.ConsumeTicketInput) *dto.ConsumeTicketOutput); ok {
		r0 = rf(ctx, command)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ConsumeTicketOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.ConsumeTicketInput) error); ok {
		r1 = rf(ctx, command)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewConsumeTicket creates a new instance of ConsumeTicket. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConsumeTicket(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConsumeTicket {
	mock := &ConsumeTicket{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
