// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	event "github.com/lucasbrito3001/ticketflow-inventory-service/internal/domain/event"
	mock "github.com/stretchr/testify/mock"

	ticket "github.com/lucasbrito3001/ticketflow-inventory-service/internal/domain/ticket"
)

// EventRepository is an autogenerated mock type for the EventRepository type
type EventRepository struct {
	mock.Mock
}

// CreateEvent provides a mock function with given fields: ctx, _a1
func (_m *EventRepository) CreateEvent(ctx context.Context, _a1 *event.Event) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *event.Event) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateEventTicketCatalogItem provides a mock function with given fields: ctx, _a1
func (_m *EventRepository) CreateEventTicketCatalogItems(ctx context.Context, _a1 *event.Event) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateEventTicketCatalogItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *event.Event) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DecrementAvailableQuantity provides a mock function with given fields: ctx, ticketType, eventID, quantityDelta
func (_m *EventRepository) DecrementAvailableQuantity(ctx context.Context, ticketType ticket.TicketType, eventID int64, quantityDelta int) error {
	ret := _m.Called(ctx, ticketType, eventID, quantityDelta)

	if len(ret) == 0 {
		panic("no return value specified for DecrementAvailableQuantity")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ticket.TicketType, int64, int) error); ok {
		r0 = rf(ctx, ticketType, eventID, quantityDelta)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindById provides a mock function with given fields: ctx, eventID
func (_m *EventRepository) FindById(ctx context.Context, eventID int64) (*event.Event, error) {
	ret := _m.Called(ctx, eventID)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 *event.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*event.Event, error)); ok {
		return rf(ctx, eventID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *event.Event); ok {
		r0 = rf(ctx, eventID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*event.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, eventID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateEvent provides a mock function with given fields: ctx, _a1
func (_m *EventRepository) UpdateEvent(ctx context.Context, _a1 *event.Event) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *event.Event) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateEventTicketCatalogItem provides a mock function with given fields: ctx, _a1
func (_m *EventRepository) UpdateEventTicketCatalogItem(ctx context.Context, _a1 *event.Event) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEventTicketCatalogItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *event.Event) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewEventRepository creates a new instance of EventRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventRepository {
	mock := &EventRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
